[package]
name = "rust-to-go"
version = "0.1.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
